import { StyleSheet } from 'react-native';

export const createStyles = (defaultHeight: number) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#f8fafc',
    },
    centerContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: '#f8fafc',
      padding: 20,
    },
    loadingText: {
      marginTop: 16,
      fontSize: 16,
      color: '#64748b',
      fontWeight: '500',
    },
    errorTitle: {
      fontSize: 22,
      fontWeight: '700',
      color: '#0f172a',
      marginTop: 16,
      marginBottom: 8,
    },
    errorText: {
      fontSize: 15,
      color: '#64748b',
      textAlign: 'center',
      marginBottom: 24,
    },
    retryButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      paddingVertical: 12,
      paddingHorizontal: 24,
      backgroundColor: '#667eea',
      borderRadius: 12,
    },
    retryButtonText: {
      fontSize: 15,
      fontWeight: '600',
      color: '#ffffff',
    },

    // Modern Header
    modernHeader: {
      paddingTop: 60,
      paddingBottom: 16,
      paddingHorizontal: 20,
      backgroundColor: '#ffffff',
      borderBottomWidth: 1,
      borderBottomColor: '#f1f5f9',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.05,
      shadowRadius: 8,
      elevation: 3,
    },
    headerContent: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    locationInfo: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      flex: 1,
    },
    locationIconWrapper: {
      width: 44,
      height: 44,
      borderRadius: 12,
      backgroundColor: '#f0f9ff',
      alignItems: 'center',
      justifyContent: 'center',
    },
    locationText: {
      flex: 1,
    },
    modernCityName: {
      fontSize: 18,
      fontWeight: '700',
      color: '#0f172a',
      letterSpacing: -0.3,
    },
    modernDistrictName: {
      fontSize: 13,
      color: '#667eea',
      fontWeight: '500',
      marginTop: 2,
    },
    modernUnsupportedBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      alignSelf: 'flex-start',
      marginTop: 4,
    },
    modernUnsupportedLabel: {
      fontSize: 11,
      color: '#f59e0b',
      fontWeight: '600',
    },
    modernRefreshButton: {
      width: 40,
      height: 40,
      borderRadius: 10,
      backgroundColor: '#f1f5f9',
      alignItems: 'center',
      justifyContent: 'center',
    },

    // Map
    mapContainer: {
      flex: 1,
    },

    // Modern Bottom Sheet
    modernBottomSheet: {
      position: 'absolute',
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: '#ffffff',
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: -4 },
      shadowOpacity: 0.1,
      shadowRadius: 12,
      elevation: 8,
    },
    modernDragHandleArea: {
      paddingVertical: 12,
      alignItems: 'center',
    },
    modernDragHandle: {
      width: 40,
      height: 5,
      backgroundColor: '#e2e8f0',
      borderRadius: 3,
    },

    // Modern Stats Bar
    modernStatsBar: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-around',
      paddingVertical: 12,
      paddingHorizontal: 20,
      marginBottom: 8,
    },
    modernStatItem: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    modernStatIcon: {
      width: 32,
      height: 32,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
    },
    modernStatNumber: {
      fontSize: 16,
      fontWeight: '700',
      color: '#0f172a',
    },
    modernStatDivider: {
      width: 1,
      height: 24,
      backgroundColor: '#e2e8f0',
    },

    // Modern Sections
    modernListScroll: {
      flex: 1,
    },
    modernSection: {
      paddingHorizontal: 20,
      marginBottom: 24,
    },
    modernSectionHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 12,
    },
    modernSectionLabel: {
      fontSize: 11,
      fontWeight: '800',
      color: '#94a3b8',
      letterSpacing: 1,
      marginBottom: 4,
    },
    modernSectionTitle: {
      fontSize: 20,
      fontWeight: '700',
      color: '#0f172a',
      letterSpacing: -0.5,
    },
    modernCountBadge: {
      paddingHorizontal: 12,
      paddingVertical: 6,
      backgroundColor: '#fee2e2',
      borderRadius: 20,
    },
    modernCountBadgeText: {
      fontSize: 13,
      fontWeight: '700',
      color: '#dc2626',
    },

    // Modern List Cards
    modernListCard: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: 14,
      backgroundColor: '#ffffff',
      borderRadius: 16,
      marginBottom: 10,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.05,
      shadowRadius: 6,
      elevation: 2,
      borderWidth: 1,
      borderColor: '#f1f5f9',
    },
    modernListIcon: {
      width: 44,
      height: 44,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 12,
    },
    modernListContent: {
      flex: 1,
    },
    modernListTitle: {
      fontSize: 15,
      fontWeight: '600',
      color: '#0f172a',
      marginBottom: 4,
    },
    modernListSubtitle: {
      fontSize: 13,
      color: '#64748b',
      lineHeight: 18,
      marginBottom: 6,
    },
    modernDistanceBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      alignSelf: 'flex-start',
      paddingHorizontal: 8,
      paddingVertical: 3,
      backgroundColor: '#f0f9ff',
      borderRadius: 8,
    },
    modernDistanceText: {
      fontSize: 11,
      fontWeight: '600',
      color: '#667eea',
    },

    // Modern Show More Button
    modernShowMoreButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      paddingVertical: 12,
      paddingHorizontal: 16,
      backgroundColor: '#f8fafc',
      borderRadius: 12,
      marginTop: 4,
      borderWidth: 1,
      borderColor: '#e2e8f0',
    },
    modernShowMoreText: {
      fontSize: 14,
      fontWeight: '600',
      color: '#667eea',
    },

    // Modern Empty State
    modernEmptyState: {
      alignItems: 'center',
      paddingVertical: 48,
      paddingHorizontal: 20,
    },
    modernEmptyIcon: {
      width: 88,
      height: 88,
      borderRadius: 44,
      backgroundColor: '#f0fdf4',
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 16,
    },
    modernEmptyTitle: {
      fontSize: 20,
      fontWeight: '700',
      color: '#0f172a',
      marginBottom: 8,
    },
    modernEmptyText: {
      fontSize: 14,
      color: '#64748b',
      textAlign: 'center',
    },

    // Modal Styles
    modalOverlay: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 20,
    },
    modalBackdrop: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: 'rgba(0, 0, 0, 0.7)',
    },
    modalContent: {
      width: '100%',
      maxWidth: 400,
      backgroundColor: '#ffffff',
      borderRadius: 24,
      padding: 24,
      maxHeight: '80%',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.3,
      shadowRadius: 20,
      elevation: 10,
    },
    modalClose: {
      position: 'absolute',
      top: -12,
      right: -12,
      zIndex: 10,
      backgroundColor: '#64748b',
      borderRadius: 16,
      width: 32,
      height: 32,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 4,
      elevation: 5,
    },
    modalHeader: {
      alignItems: 'center',
      marginBottom: 20,
    },
    modalIcon: {
      width: 72,
      height: 72,
      borderRadius: 36,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 16,
    },
    modalTitle: {
      fontSize: 22,
      fontWeight: '700',
      color: '#0f172a',
      textAlign: 'center',
      marginBottom: 8,
      lineHeight: 28,
    },
    modalDistanceBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingHorizontal: 12,
      paddingVertical: 6,
      backgroundColor: '#f0f9ff',
      borderRadius: 12,
    },
    modalDistanceText: {
      fontSize: 13,
      fontWeight: '600',
      color: '#667eea',
    },
    modalScroll: {
      maxHeight: 300,
    },
    modalDescription: {
      fontSize: 15,
      color: '#475569',
      lineHeight: 24,
      textAlign: 'center',
      marginBottom: 24,
    },
    modalInfo: {
      gap: 16,
    },
    modalInfoItem: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      padding: 16,
      backgroundColor: '#f8fafc',
      borderRadius: 16,
    },
    modalInfoIcon: {
      width: 40,
      height: 40,
      borderRadius: 12,
      backgroundColor: '#e0e7ff',
      alignItems: 'center',
      justifyContent: 'center',
    },
    modalInfoLabel: {
      fontSize: 12,
      color: '#94a3b8',
      fontWeight: '500',
      marginBottom: 2,
    },
    modalInfoValue: {
      fontSize: 15,
      color: '#0f172a',
      fontWeight: '600',
    },

    // Old styles kept for compatibility
    header: {
      paddingTop: 60,
      paddingBottom: 16,
      paddingHorizontal: 20,
      backgroundColor: '#ffffff',
      borderBottomWidth: 1,
      borderBottomColor: '#f0f0f0',
    },
    cityName: {
      fontSize: 16,
      fontWeight: '600',
      color: '#1a1a1a',
    },
    districtName: {
      fontSize: 13,
      color: '#667eea',
      marginTop: 2,
    },
    unsupportedLabel: {
      fontSize: 12,
      color: '#f59e0b',
      fontStyle: 'italic',
    },
    refreshButton: {
      width: 40,
      height: 40,
      borderRadius: 10,
      backgroundColor: '#f5f5f5',
      alignItems: 'center',
      justifyContent: 'center',
    },
    unsupportedBanner: {
      position: 'absolute',
      top: 130,
      left: 20,
      right: 20,
      zIndex: 10,
    },
    bannerContent: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      paddingVertical: 12,
      paddingHorizontal: 16,
      backgroundColor: '#fff',
      borderRadius: 12,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    bannerText: {
      flex: 1,
      fontSize: 13,
      color: '#1a1a1a',
      fontWeight: '500',
    },
    bannerLink: {
      fontSize: 13,
      color: '#667eea',
      fontWeight: '600',
    },
    bottomSheet: {
      position: 'absolute',
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: '#ffffff',
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: -2 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 5,
    },
    dragHandleArea: {
      paddingVertical: 12,
      alignItems: 'center',
    },
    dragHandle: {
      width: 40,
      height: 5,
      backgroundColor: '#e0e0e0',
      borderRadius: 3,
    },
    statsBar: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-around',
      paddingVertical: 10,
      paddingHorizontal: 20,
      borderBottomWidth: 1,
      borderBottomColor: '#f0f0f0',
    },
    statItem: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    statNumber: {
      fontSize: 14,
      fontWeight: '600',
      color: '#1a1a1a',
    },
    statDivider: {
      width: 1,
      height: 20,
      backgroundColor: '#e0e0e0',
    },
    listScroll: {
      flex: 1,
    },
    section: {
      paddingHorizontal: 20,
      marginBottom: 20,
    },
    sectionHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 12,
    },
    sectionTitle: {
      fontSize: 16,
      fontWeight: '600',
      color: '#1a1a1a',
    },
    showMoreButton: {
      fontSize: 13,
      fontWeight: '600',
      color: '#667eea',
    },
    listCard: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: 12,
      backgroundColor: '#ffffff',
      borderRadius: 12,
      marginBottom: 8,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 4,
      elevation: 2,
    },
    listIcon: {
      width: 40,
      height: 40,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 12,
    },
    listContent: {
      flex: 1,
    },
    listTitle: {
      fontSize: 14,
      fontWeight: '600',
      color: '#1a1a1a',
      marginBottom: 4,
    },
    listSubtitle: {
      fontSize: 13,
      color: '#666',
      marginBottom: 4,
    },
    listDistance: {
      fontSize: 12,
      color: '#667eea',
      fontWeight: '500',
    },
    emptyState: {
      alignItems: 'center',
      paddingVertical: 40,
    },
    emptyTitle: {
      fontSize: 18,
      fontWeight: '600',
      color: '#1a1a1a',
      marginTop: 12,
    },
    emptyText: {
      fontSize: 14,
      color: '#666',
      marginTop: 6,
      textAlign: 'center',
    },
    detailContainer: {
      flex: 1,
    },
    backButton: {
      position: 'absolute',
      top: 16,
      left: 20,
      zIndex: 10,
      width: 36,
      height: 36,
      borderRadius: 10,
      backgroundColor: '#f5f5f5',
      alignItems: 'center',
      justifyContent: 'center',
    },
    detailScroll: {
      flex: 1,
    },
    detailContent: {
      alignItems: 'center',
      paddingTop: 60,
      paddingHorizontal: 20,
      paddingBottom: 40,
    },
    detailIcon: {
      width: 80,
      height: 80,
      borderRadius: 20,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 16,
    },
    detailBadge: {
      paddingHorizontal: 14,
      paddingVertical: 6,
      backgroundColor: '#f0f0f0',
      borderRadius: 12,
      marginBottom: 16,
    },
    detailBadgeText: {
      fontSize: 11,
      fontWeight: '700',
      color: '#666',
      letterSpacing: 0.5,
    },
    detailTitle: {
      fontSize: 24,
      fontWeight: '700',
      color: '#1a1a1a',
      textAlign: 'center',
      marginBottom: 12,
    },
    distanceBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingHorizontal: 12,
      paddingVertical: 6,
      backgroundColor: '#f0f9ff',
      borderRadius: 10,
      marginBottom: 16,
    },
    distanceText: {
      fontSize: 13,
      fontWeight: '600',
      color: '#667eea',
    },
    detailDescription: {
      fontSize: 16,
      color: '#4a4a4a',
      lineHeight: 24,
      textAlign: 'center',
      marginBottom: 24,
    },
    infoBox: {
      width: '100%',
      padding: 16,
      backgroundColor: '#f8f8f8',
      borderRadius: 12,
      marginBottom: 16,
    },
    infoBoxTitle: {
      fontSize: 14,
      fontWeight: '600',
      color: '#1a1a1a',
      marginBottom: 8,
    },
    infoBoxText: {
      fontSize: 14,
      color: '#4a4a4a',
      lineHeight: 20,
    },
    detailMeta: {
      fontSize: 13,
      color: '#999',
      textAlign: 'center',
    },
  });